# Generated by Django 5.2.7 on 2025-10-12 19:28

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('institution', models.CharField(blank=True, max_length=150, null=True)),
                ('user_type', models.CharField(choices=[('Estudante', 'Estudante'), ('Professor', 'Professor'), ('Organizador', 'Organizador')], default='Estudante', max_length=20, verbose_name='Tipo de Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Usuário',
                'verbose_name_plural': 'Registros de Usuário',
                'db_table': 'user_register',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('initial_date', models.DateField(default='9999-12-31', verbose_name='Data de Início')),
                ('final_date', models.DateField(default='9999-12-31', verbose_name='Data Final')),
                ('location', models.CharField(max_length=200, verbose_name='Local')),
                ('max_capacity', models.IntegerField(verbose_name='Capacidade Máxima')),
                ('event_type', models.CharField(choices=[('Palestra', 'Palestra'), ('Workshop', 'Workshop'), ('Seminário', 'Seminário'), ('Curso', 'Curso'), ('Congresso', 'Congresso'), ('Simpósio', 'Simpósio'), ('Fórum', 'Fórum'), ('Mesa Redonda', 'Mesa Redonda')], default='Palestra', max_length=20, verbose_name='Tipo de Evento')),
                ('event_start', models.TimeField(blank=True, verbose_name='Horario de Início')),
                ('event_end', models.TimeField(blank=True, verbose_name='Horario de Término')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'event',
                'ordering': ['initial_date'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('participant', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='attended_events', through='app.EventParticipant', through_fields=('event', 'participant'), to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'db_table': 'EventRegister',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='Data de Emissão')),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de Verificação')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Participante')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificate',
                'ordering': ['-issue_date'],
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
