# Generated by Django 5.2.7 on 2025-10-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='login',
            options={'ordering': ['username'], 'verbose_name': 'Login', 'verbose_name_plural': 'Logins'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['name'], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
        migrations.AlterModelTable(
            name='registration',
            table='registration',
        ),
    ]
