# Generated by Django 5.2.7 on 2025-10-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_craetor_event_max_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='craetor',
            new_name='creator',
        ),
    ]
