# Generated by Django 5.2.7 on 2025-11-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
