# Generated by Django 5.2.7 on 2025-10-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('institution', models.CharField(blank=True, max_length=150, null=True)),
                ('type_user', models.BooleanField()),
            ],
            options={
                'verbose_name': 'User Register',
                'verbose_name_plural': 'User Registers',
                'db_table': 'user_register',
                'ordering': ['username'],
            },
        ),
        migrations.RenameModel(
            old_name='Registration',
            new_name='EventRegister',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='register',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['initial_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventregister',
            options={'ordering': ['name'], 'verbose_name': 'Event Registration', 'verbose_name_plural': 'Event Registrations'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Palestra', 'Palestra'), ('Workshop', 'Workshop'), ('Seminário', 'Seminário'), ('Curso', 'Curso'), ('Congresso', 'Congresso'), ('Simpósio', 'Simpósio'), ('Fórum', 'Fórum'), ('Mesa Redonda', 'Mesa Redonda')], default='Palestra', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='final_date',
            field=models.DateTimeField(default='9999-12-31 23:59:59'),
        ),
        migrations.AddField(
            model_name='event',
            name='hours_event',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='initial_date',
            field=models.DateTimeField(default='9999-12-31 00:00:00'),
        ),
        migrations.AlterModelTable(
            name='eventregister',
            table='EventRegister',
        ),
    ]
