# Generated by Django 5.2.7 on 2025-11-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userregister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
