# Generated by Django 5.2.7 on 2025-10-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userregister_rename_registration_eventregister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='type_user',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Professor', 'Professor')], default='Palestra', max_length=20),
        ),
    ]
