# Generated by Django 5.2.7 on 2025-11-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userregister_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='professor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Professor Responsável'),
        ),
    ]
