# Generated by Django 5.2.7 on 2025-10-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userregister_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default='9999-12-31 23:59:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregister',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregister',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='type_user',
            field=models.BooleanField(default=False),
        ),
    ]
