<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-08 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userregister_date_joined_userregister_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='type_user',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Professor', 'Professor')], default='Estudante', max_length=20),
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
=======
# Generated by Django 5.2.7 on 2025-10-08 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userregister_date_joined_userregister_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='type_user',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Professor', 'Professor')], default='Estudante', max_length=20),
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
>>>>>>> 5a96fedf93e6b0de9087d57868d0edb4fd6311c1
