# Generated by Django 5.2.7 on 2025-11-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_event_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='professor',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True, verbose_name='Professor Responsável'),
        ),
    ]
