# Generated by Django 5.2.7 on 2025-11-13 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_event_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'Professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructed_events', to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável'),
        ),
    ]
