# Generated by Django 5.2.7 on 2025-10-08 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_event_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='eventos_participados', through='app.EventParticipant', through_fields=('event', 'participant'), to=settings.AUTH_USER_MODEL),
        ),
    ]
