# Generated by Django 5.2.7 on 2025-10-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='userregister',
            name='type_user',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Professor', 'Professor'), ('Organizador', 'Organizador')], default='Estudante', max_length=20),
        ),
    ]
