# Generated by Django 5.2.8 on 2025-12-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_finalized',
            field=models.BooleanField(default=False, verbose_name='Evento Finalizado'),
        ),
    ]
