# Generated by Django 5.2.7 on 2025-10-09 15:09

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_userregister_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(default=datetime.date.today, verbose_name='Data de Emissão')),
                ('codigo_verificacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de Verificação')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='app.event', verbose_name='Evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Participante')),
            ],
        ),
    ]
