# Generated by Django 5.2.8 on 2025-12-06 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_event_event_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='Código de Verificação'),
        ),
    ]
