# Generated by Django 5.2.7 on 2025-10-09 15:21

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_certificado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['initial_date'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='userregister',
            options={'ordering': ['username'], 'verbose_name': 'Registro de Usuário', 'verbose_name_plural': 'Registros de Usuário'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='hours_event',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='type_user',
        ),
        migrations.AddField(
            model_name='event',
            name='event_duration',
            field=models.TimeField(blank=True, default='00:00:00', verbose_name='Carga Horária'),
        ),
        migrations.AddField(
            model_name='userregister',
            name='user_type',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Professor', 'Professor'), ('Organizador', 'Organizador')], default='Estudante', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Palestra', 'Palestra'), ('Workshop', 'Workshop'), ('Seminário', 'Seminário'), ('Curso', 'Curso'), ('Congresso', 'Congresso'), ('Simpósio', 'Simpósio'), ('Fórum', 'Fórum'), ('Mesa Redonda', 'Mesa Redonda')], default='Palestra', max_length=20, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='final_date',
            field=models.DateTimeField(default='9999-12-31 23:59:59', verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='event',
            name='initial_date',
            field=models.DateTimeField(default='9999-12-31 00:00:00', verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_capacity',
            field=models.IntegerField(verbose_name='Capacidade Máxima'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='attended_events', through='app.EventParticipant', through_fields=('event', 'participant'), to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='Data de Emissão')),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de Verificação')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app.event', verbose_name='Evento')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificate',
                'ordering': ['-issue_date'],
                'unique_together': {('event', 'participant')},
            },
        ),
        migrations.DeleteModel(
            name='Certificado',
        ),
    ]
