# Generated by Django 5.2.7 on 2025-10-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_event_final_date_alter_event_initial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='final_date',
            field=models.DateTimeField(default='9999-12-31', verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='event',
            name='initial_date',
            field=models.DateTimeField(default='9999-12-31', verbose_name='Data de Início'),
        ),
    ]
