# Generated by Django 5.2.7 on 2025-10-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_event_final_date_alter_event_initial_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_duration',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end',
            field=models.TimeField(blank=True, default='00:00:00', verbose_name='Horario de Término'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_start',
            field=models.TimeField(blank=True, default='00:00:00', verbose_name='Horario de Início'),
            preserve_default=False,
        ),
    ]
